### ISSUE TITLE
there is no speck.h in project

### ISSUE THREAD

**Issue by GYUMO** [atbarker/AONT-RS#2]
no speck.h in the project where it is needed in aont.h

aont.h:6:10: fatal error: speck.h: No such file or directory
 #include "speck.h"
          ^~~~~~~~~
compilation terminated.

**Comment by atbarker** [comment]
Sorry, the curse of doing almost all your work alone on one computer is that sometimes you forget to add files. It used to use the kernel crypto API passthrough library but speck is such a small a portable cipher that I could easily eliminate a dependency.

I added the missing files.
